2019-12-14 10:10:48 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Menu.menuSelection(Menu.java:52)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 10:48:33 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Menu.menuSelection(Menu.java:52)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 11:04:15 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Menu.menuSelection(Menu.java:52)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 19:56:27 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Actions.CustomerOptions.newCustomerActions(CustomerOptions.java:48)
	at com.revature.Menu.menuSelection(Menu.java:26)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 20:36:40 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Actions.CustomerOptions.newCustomerActions(CustomerOptions.java:48)
	at com.revature.Menu.menuSelection(Menu.java:26)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 20:46:31 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Actions.CustomerOptions.newCustomerActions(CustomerOptions.java:48)
	at com.revature.Menu.menuSelection(Menu.java:26)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 20:51:16 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Actions.CustomerOptions.newCustomerActions(CustomerOptions.java:48)
	at com.revature.Menu.menuSelection(Menu.java:26)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 21:01:37 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Actions.CustomerOptions.newCustomerActions(CustomerOptions.java:48)
	at com.revature.Menu.menuSelection(Menu.java:26)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 21:14:42 WARN  DBService:26 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:36)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Actions.CustomerOptions.newCustomerActions(CustomerOptions.java:48)
	at com.revature.Menu.menuSelection(Menu.java:26)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 21:23:48 WARN  DBService:74 - Unable to add account
org.postgresql.util.PSQLException: ERROR: column "type" of relation "accounts" does not exist
  Position: 23
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.revature.bankingapplication.DBService.addAccount(DBService.java:56)
	at com.revature.bankingapplication.Bank.addAccount(Bank.java:14)
	at com.revature.Actions.CustomerOptions.newCustomerActions(CustomerOptions.java:48)
	at com.revature.Menu.menuSelection(Menu.java:26)
	at com.revature.Driver.main(Driver.java:7)
2019-12-14 21:48:58 WARN  DBService:147 - Unable to update account
org.postgresql.util.PSQLException: ERROR: syntax error at or near "Users"
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.revature.bankingapplication.DBService.deleteAccount(DBService.java:144)
	at com.revature.bankingapplication.Bank.deleteAccount(Bank.java:26)
	at com.revature.Actions.UserOptions.userActions(UserOptions.java:52)
	at com.revature.Menu.menuSelection(Menu.java:30)
	at com.revature.Driver.main(Driver.java:7)
2019-12-16 12:44:58 WARN  DBService:176 - Unable to update account
org.postgresql.util.PSQLException: ERROR: syntax error at or near "Users"
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.revature.bankingapplication.DBService.deleteAccount(DBService.java:173)
	at com.revature.bankingapplication.Bank.deleteAccount(Bank.java:27)
	at com.revature.Actions.UserOptions.userActions(UserOptions.java:59)
	at com.revature.Menu.menuSelection(Menu.java:30)
	at com.revature.Driver.main(Driver.java:7)
2019-12-16 14:55:24 WARN  DBService:26 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.updateStatus(DBService.java:131)
	at com.revature.bankingapplication.Bank.updateStatus(Bank.java:77)
	at com.revature.Actions.EmployeeOptions.employeeActions(EmployeeOptions.java:48)
	at com.revature.Menu.menuSelection(Menu.java:35)
	at com.revature.Driver.main(Driver.java:7)
2019-12-16 14:56:18 WARN  DBService:26 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.getAccount(DBService.java:83)
	at com.revature.bankingapplication.Bank.getAccount(Bank.java:18)
	at com.revature.Actions.UserOptions.userActions(UserOptions.java:43)
	at com.revature.Menu.menuSelection(Menu.java:31)
	at com.revature.Driver.main(Driver.java:7)
2019-12-16 16:29:02 WARN  DBService:26 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.getAccount(DBService.java:86)
	at com.revature.bankingapplication.Bank.getAccount(Bank.java:18)
	at com.revature.Actions.UserOptions.userActions(UserOptions.java:31)
	at com.revature.Menu.menuSelection(Menu.java:31)
	at com.revature.Driver.main(Driver.java:7)
2019-12-16 16:46:43 WARN  DBService:26 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.getAccount(DBService.java:86)
	at com.revature.bankingapplication.Bank.getAccount(Bank.java:18)
	at com.revature.Actions.UserOptions.userActions(UserOptions.java:31)
	at com.revature.Menu.menuSelection(Menu.java:31)
	at com.revature.Driver.main(Driver.java:7)
2019-12-16 17:04:37 WARN  DBService:26 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.bankingapplication.DBService.connect(DBService.java:24)
	at com.revature.bankingapplication.DBService.getAccount(DBService.java:86)
	at com.revature.bankingapplication.Bank.getAccount(Bank.java:18)
	at com.revature.Actions.UserOptions.userActions(UserOptions.java:31)
	at com.revature.Menu.menuSelection(Menu.java:31)
	at com.revature.Driver.main(Driver.java:7)
2019-12-17 13:36:35 INFO  UserOptions:33 - Succesful log in attempt
2019-12-17 13:36:41 INFO  UserOptions:50 - Account 7 retrieved succesfully
2019-12-17 13:57:43 INFO  EmployeeOptions:27 - Succesful employee account verification
2019-12-17 13:57:55 WARN  DBService:212 - Unable to retrieve all accounts
2019-12-17 13:57:55 INFO  EmployeeOptions:42 - Succesfully retrieved all accounts
2019-12-17 14:00:22 INFO  CustomerOptions:55 - Succesfully created new account
2019-12-17 14:01:03 INFO  UserOptions:119 - Failed user account verification
2019-12-17 14:01:16 INFO  UserOptions:33 - Succesful user account verification
2019-12-17 14:01:47 INFO  UserOptions:50 - Account 8 retrieved succesfully
2019-12-17 14:02:07 INFO  UserOptions:33 - Succesful user account verification
2019-12-17 14:02:17 INFO  UserOptions:58 - Succesfully deposited 1000 into account 8
2019-12-17 14:02:59 INFO  UserOptions:119 - Failed user account verification
2019-12-17 14:03:27 INFO  UserOptions:33 - Succesful user account verification
2019-12-17 14:49:33 INFO  UserOptions:33 - Succesful user account verification
2019-12-17 15:12:36 INFO  CustomerOptions:62 - Succesfully created new account
2019-12-17 15:18:02 INFO  CustomerOptions:58 - Succesfully created new account
